version: "3.8"
services:
  python-app:
    build:
      context: .
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ~/.ssh:/root/.ssh
      - .:/app
    ports:
      - "5000:5000"
    command: python app.py
    entrypoint: ["/bin/bash", "/app/entrypoint.sh"]