services:
  python-app:
    build:
      context: .
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: hatch run python app.py
    entrypoint: ["/bin/bash", "/app/entrypoint.sh"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev  # Use the development Dockerfile
    volumes:
      - ./frontend:/app  # Mount local frontend source for live development
      - /app/node_modules  # Prevent node_modules from being overwritten
    ports:
      - "3000:3000"  # Map React's development server port
    environment:
      - CHOKIDAR_USEPOLLING=true  # Required for file watching in some setups
    command: npm start  # Start React development server
    depends_on:
      - python-app

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - python-app