[default]
log_level = "INFO"

source_data_file = "/workspaces/ClassicalComposer/data/Challenge_DataSet.zip"
data_folder = "/workspaces/ClassicalComposer/data/Challenge_DataSet"
static_folder = "/workspaces/ClassicalComposer/static"
resource_folder = "/workspaces/ClassicalComposer/resources"

kmeans_model = "models/kmeans_model_run.pkl"
cnn_model = "models/cnn_model.keras"

start_server = false
generate_dataset = false
train_kmeans = false
train_cnn = false